import React from "react";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";

interface PDFReportProps {
    report: {
        title: string;
        num_rows: number;
        columns: string[];
        uploaded_at: string;
    };
    summary: {
        summary: string;
        metrics: string[];
        trends: string[];
        recommendations: string[];
    };
}

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontSize: 11,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: 2,
        borderBottomColor: '#000',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 10,
        color: '#666',
        marginBottom:3,
    },
    section: { 
        marginTop: 20,
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#000',
        backgroundColor: '#f0f0f0',
        padding: 8,
    },
    text: {
        lineHeight: 1.5,
        marginBottom: 8,
    },
    bulletPoint: {
        flexDirection: 'row',
        marginBottom: 6,
        paddingLeft: 10,
    },
    bullet: {
        width: 15,
        fontSize: 12,
    },
    bulletText: {
        flec: 1,
        lineHeight: 14,
    },
    metricBox: {
        backgroundColor: '#f8f8f8',
        padding: 10,
        marginBottom: 8,
        borderRadius: 4,
        border: 1,
        borderColor: '#e0e0e0',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 9,
        color: '#999',
        borderTop: 1,
        borderTopColor: '#ddd',
        paddingTop: 10,
    }
});

const PDFReport: React.FC<PDFReportProps> = ({ report, summary }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>ReportBrief AI Summary</Text>
                <Text style={styles.subtitle}>{report.title}</Text>
                <Text style={styles.subtitle}>
                    Generated: {new Date().toLocaleDateString()} | Rows: {report.num_rows.toLocaleString()} | Columns: {report.columns.length}
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>📊 Key Metrics</Text>

                {summary.metrics.map((metric, idx) => (
                <View key={idx} style={styles.metricBox}>
                    <Text>{metric}</Text>
                </View>
                ))}

            </View>
            
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>📈 Notable Trends</Text>

                {summary.trends.map((trend, idx) => (
                <View key={idx} style={styles.bulletPoint}>
                    <Text style={styles.bullet}>•</Text>
                    <Text style={styles.bulletText}>{trend}</Text>
                </View>
                ))}

            </View>
            
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>💡 Actionable Recommendations</Text>

                {summary.recommendations.map((rec, idx) => (
                <View key={idx} style={styles.bulletPoint}>
                    <Text style={styles.bullet}>→</Text>
                    <Text style={styles.bulletText}>{rec}</Text>
                </View>
                ))}

            </View>
            
            <View style={styles.footer}>
                <Text>Generated by ReportBrief | https://reportbrief.com</Text>
                <Text>Uploaded: {new Date(report.uploaded_at).toLocaleDateString()}</Text>
            </View>
        </Page>
    </Document>
);

// function to generate and download PDF
export const downloadPDF = async (report: PDFReportProps['report'], summary: PDFReportProps['summary']) => {
    const blob = await pdf(<PDFReport report={report} summary={summary} />).toBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    link.href = url;
    link.download = `${report.title.replace(/[^a-z0-9]/gi, '_')}_summary.pdf`;
    link.click();
    
    URL.revokeObjectURL(url);
};

export default PDFReport;